### ISSUE TITLE
How to use Wikipedia as source of commits?

### ISSUE THREAD

**Issue by schollz** [jubalh/gontributions#13]

**Comment by jubalh** [comment]
Indeed I have to say that this can be confusing for some users.
Some MediaWiki instances have their API at `URL` where others have it at `URL/w`.
You can find an example on how to query Wikipedia in the USAGE.md now :)

This issue made me create a USAGE.md https://github.com/jubalh/gontributions/commit/e58cf30a7bb76df46d5ce84fbebc81a2c63ed9d7

Thanks for coming up with that question :)

**Comment by jubalh** [comment]
If this solves your issue feel free to close it or ask more questions :)

**Comment by schollz** [comment]
Thanks! That's really helpful.

What about adding support for distinguishing the pages that have been contributed to? E.g. using [this api call](https://wiki.lxde.org/en/api.php?action=query&list=usercontribs&ucuser=Jubalh&uclimit=3&ucdir=newer&format=json) for getting `usercontribs`, and then parsing that to deliver number of contributions for each different page.

**Comment by jubalh** [comment]
It is a good idea.
It belongs to issue https://github.com/jubalh/gontributions/issues/10 I would say.
There are two things for this: we wil have to carry more information in the structures instead of only 'commits'. I mean so far we only carry the number of commits with us and in this case 'contribution' needs to be probably another structure with all the infos about one such contribution.
Second this needs a new template which then will display all this information.
And this needs to be done in a way not to break the existing default and detailed template.

**Comment by schollz** [comment]
Agreed, I'll close this issue then and move the discussion there.
